server:
  port: 8080

spring:
  application:
    name: api-gateway
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: chat-service-route
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**

        - id: search-service-route
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**

        - id: ws-handler-service-route
          uri: lb://ws-handler-service
          predicates:
            - Path=/ws/**
